export const ADD_TODO = "APP/ADD_TODO";
export const TOGGLE_TODO = "APP/TOGGLE_TODO";
export const REMOVE_TODO = "APP/REMOVE_TODO";
export const SET_DAY = "APP/SET_DAY";

// Fetch date from server

export const FETCH_DATE_START = "APP/FETCH_DATE_START";
export const FETCH_DATE_SUCCESS = "APP/FETCH_DATE_SUCCESS";
export const FETCH_DATE_ERROR = "APP/FETCH_DATE_ERROR";

export const CREATE_TODO_START = "APP/CREATE_TODO_START";
export const CREATE_TODO_SUCCESS = "APP/CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR = "APP/CREATE_TODO_ERROR";
